const CartActionTypes = {
  TOGGLE_CART_IS_HIDDEN: 'TOGGLE_CART_IS_HIDDEN',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  DECREASE_ITEM_QUANTITY: 'DECREASE_ITEM_QUANTITY',
  INCREASE_ITEM_QUANTITY: 'INCREASE_ITEM_QUANTITY',
}

export default CartActionTypes;